### ISSUE TITLE
Static repositories doesn't have separate cache version

### ISSUE THREAD

**Issue by adya** [tmspzz/Rome#203]
## Bug Report 

Rome doesn't add `static` suffix as said [here](https://github.com/tmspzz/Rome#cache-structure): 

> `<git-repository-name>/.<framework-name>.version-(static-)<version-hash>`

**Steps which reproduce the bug**

1. Set in Romefile `repositoryMap`:
```
- Dependency:
    - name: Dependency
      type: static
```
2. Build a static framework using techniques like [this](https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md)
3. Perform `rome upload --platform iOS --cache-prefix RomeCache`. 

**Current behavior**

I use a custom engine to upload artifacts to `Nexus` repository, so in my script, there is logging which outputs exactly the paths that Rome provides to its engine:
```
Uploading file from RomeCache/Dependency/iOS/Dependency.framework-static-7.0.0.zip
Uploading file from RomeCache/Dependency/.Dependency.version-7.0.0 
```
I have multiple build configurations that build the `Dependency` both as static and dynamic.
And in this scenario, it leads to a collision of `.version` file so, after performing steps to reproduce this issue and switching back to config that builds `Dependency` as dynamic framework,
doing `rome download --platform iOS --cache-prefix RomeCache` will make Carthage think that there is a valid `Dependency.framework` cache (according to `.Dependency.version-7.0.0` file), but in fact, there is no cache for dynamic `Dependency.framework` and project compilation fails.

**Suggested behavior**
   Well, I guess Rome should honor type of the framework when managing `.verion` file the same way it does for `.framework`.

**Rome version:** 

    0.23.1.61

**OS and version:** 

    macOS Mojave 10.14.4

**Comment by tmspzz** [comment]
Thanks, I'll look into it

**Comment by tmspzz** [comment]
So this is a combined problem.

1) Currently .version files for static frameworks don't work https://github.com/Carthage/Carthage/pull/2900

2) This naming scheme `<git-repository-name>/.<framework-name>.version-(static-)<version-hash>` is not valid as the .version file is over the entire products of `Dependency`. This is my mistake in the documentation.

As for your case I'm not sure why carthage would think that the .version file is valid. It shouldn't because the hashes should be different. 

Can you run `shasum -a 256 Depdency.framework/Depdency` for both the dynamic and static build? The hashes should differ.

Anyways you have 2 options:
- wait for the bug in carthage to be fixed and have 2 build configurations that will result in 2 entries in the .versionfile 
- don't wait and use a different `cache-prefix`

**Comment by adya** [comment]
Hi, thanks for the quick reply :) Yes, for now, I'm using separate `cache-prefix` for each config.

As for SHA, they are indeed different.

Thanks, for pointing to `Carthage` issue, I've mistakenly assumed that the issue is on the `Rome` side.
Should we close this issue then? Or better leave it and track whether it will work when Carthage provides support for static versions?

**Comment by tmspzz** [comment]
When carthage will work properly this should work well by itself.

@adya I'll be glad if you could close the issue
